trigger:
- master

pool:
  name: Default
  vmImage: 'ubuntu-latest'

jobs:
- job: MisraCheck
  displayName: Check for Misra Compliance

  steps:

  - script: |
      sudo apt-get install cppcheck
    displayName: 'Install cppcheck'

  - script: |
      cppcheck --error-exitcode=1 --addon=misra.json .
    displayName: 'Run cppcheck'
